// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxC8VvI1rLZKpzVzMT6KUYjOnaZjGqh5g',
    appId: '1:1032803103136:web:49d621e8186668fec974c5',
    messagingSenderId: '1032803103136',
    projectId: 'otakuuniverse-d82e0',
    authDomain: 'otakuuniverse-d82e0.firebaseapp.com',
    storageBucket: 'otakuuniverse-d82e0.firebasestorage.app',
    measurementId: 'G-2E6GC4421R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeFyt44KV99ZT9FslErIgot-oAWDdDIs4',
    appId: '1:1032803103136:android:5437ce7bc8f00eb2c974c5',
    messagingSenderId: '1032803103136',
    projectId: 'otakuuniverse-d82e0',
    storageBucket: 'otakuuniverse-d82e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQM0pkg_e9h-yaSEPGWhWQXgTiDbZ6D-k',
    appId: '1:1032803103136:ios:529ef2facc0d7f92c974c5',
    messagingSenderId: '1032803103136',
    projectId: 'otakuuniverse-d82e0',
    storageBucket: 'otakuuniverse-d82e0.firebasestorage.app',
    iosBundleId: 'com.example.otakuUniverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQM0pkg_e9h-yaSEPGWhWQXgTiDbZ6D-k',
    appId: '1:1032803103136:ios:529ef2facc0d7f92c974c5',
    messagingSenderId: '1032803103136',
    projectId: 'otakuuniverse-d82e0',
    storageBucket: 'otakuuniverse-d82e0.firebasestorage.app',
    iosBundleId: 'com.example.otakuUniverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxC8VvI1rLZKpzVzMT6KUYjOnaZjGqh5g',
    appId: '1:1032803103136:web:f2d3a43c38eb0241c974c5',
    messagingSenderId: '1032803103136',
    projectId: 'otakuuniverse-d82e0',
    authDomain: 'otakuuniverse-d82e0.firebaseapp.com',
    storageBucket: 'otakuuniverse-d82e0.firebasestorage.app',
    measurementId: 'G-FYPQ9MJ3VK',
  );
}
